# Generated by Django 4.0 on 2022-01-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['name'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
    ]
